/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminWarehousesRouteImport } from './routes/admin.warehouses'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminStockMovementsRouteImport } from './routes/admin.stock-movements'
import { Route as AdminStockAdjustmentsRouteImport } from './routes/admin.stock-adjustments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin.purchase-orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOtpRouteImport } from './routes/admin.otp'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLockRouteImport } from './routes/admin.lock'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminForecastRouteImport } from './routes/admin.forecast'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBulkOperationsRouteImport } from './routes/admin.bulk-operations'
import { Route as AdminBatchesRouteImport } from './routes/admin.batches'
import { Route as AdminBarcodesRouteImport } from './routes/admin.barcodes'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountWalletRouteImport } from './routes/account.wallet'
import { Route as AccountTrackingRouteImport } from './routes/account.tracking'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountReturnsRouteImport } from './routes/account.returns'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountInvoicesRouteImport } from './routes/account.invoices'
import { Route as AccountCouponsRouteImport } from './routes/account.coupons'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehousesRoute = AdminWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockMovementsRoute = AdminStockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockAdjustmentsRoute = AdminStockAdjustmentsRouteImport.update({
  id: '/stock-adjustments',
  path: '/stock-adjustments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOtpRoute = AdminOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLockRoute = AdminLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForecastRoute = AdminForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkOperationsRoute = AdminBulkOperationsRouteImport.update({
  id: '/bulk-operations',
  path: '/bulk-operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarcodesRoute = AdminBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWalletRoute = AccountWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTrackingRoute = AccountTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInvoicesRoute = AccountInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCouponsRoute = AccountCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/coupons': typeof AccountCouponsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/tracking': typeof AccountTrackingRoute
  '/account/wallet': typeof AccountWalletRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/barcodes': typeof AdminBarcodesRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/bulk-operations': typeof AdminBulkOperationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock-adjustments': typeof AdminStockAdjustmentsRoute
  '/admin/stock-movements': typeof AdminStockMovementsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/coupons': typeof AccountCouponsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/tracking': typeof AccountTrackingRoute
  '/account/wallet': typeof AccountWalletRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/barcodes': typeof AdminBarcodesRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/bulk-operations': typeof AdminBulkOperationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock-adjustments': typeof AdminStockAdjustmentsRoute
  '/admin/stock-movements': typeof AdminStockMovementsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/coupons': typeof AccountCouponsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/tracking': typeof AccountTrackingRoute
  '/account/wallet': typeof AccountWalletRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/barcodes': typeof AdminBarcodesRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/bulk-operations': typeof AdminBulkOperationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock-adjustments': typeof AdminStockAdjustmentsRoute
  '/admin/stock-movements': typeof AdminStockMovementsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/coupons'
    | '/account/invoices'
    | '/account/notifications'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/settings'
    | '/account/support'
    | '/account/tracking'
    | '/account/wallet'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/barcodes'
    | '/admin/batches'
    | '/admin/bulk-operations'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forecast'
    | '/admin/forgot-password'
    | '/admin/inventory'
    | '/admin/lock'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/otp'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/stock-adjustments'
    | '/admin/stock-movements'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/warehouses'
    | '/category/$slug'
    | '/product/$slug'
    | '/account/'
    | '/admin/'
    | '/admin/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/coupons'
    | '/account/invoices'
    | '/account/notifications'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/settings'
    | '/account/support'
    | '/account/tracking'
    | '/account/wallet'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/barcodes'
    | '/admin/batches'
    | '/admin/bulk-operations'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forecast'
    | '/admin/forgot-password'
    | '/admin/inventory'
    | '/admin/lock'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/otp'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/stock-adjustments'
    | '/admin/stock-movements'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/warehouses'
    | '/category/$slug'
    | '/product/$slug'
    | '/account'
    | '/admin'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/coupons'
    | '/account/invoices'
    | '/account/notifications'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/settings'
    | '/account/support'
    | '/account/tracking'
    | '/account/wallet'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/barcodes'
    | '/admin/batches'
    | '/admin/bulk-operations'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forecast'
    | '/admin/forgot-password'
    | '/admin/inventory'
    | '/admin/lock'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/otp'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/stock-adjustments'
    | '/admin/stock-movements'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/warehouses'
    | '/category/$slug'
    | '/product/$slug'
    | '/account/'
    | '/admin/'
    | '/admin/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouses': {
      id: '/admin/warehouses'
      path: '/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AdminWarehousesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-movements': {
      id: '/admin/stock-movements'
      path: '/stock-movements'
      fullPath: '/admin/stock-movements'
      preLoaderRoute: typeof AdminStockMovementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-adjustments': {
      id: '/admin/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/admin/stock-adjustments'
      preLoaderRoute: typeof AdminStockAdjustmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/otp': {
      id: '/admin/otp'
      path: '/otp'
      fullPath: '/admin/otp'
      preLoaderRoute: typeof AdminOtpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lock': {
      id: '/admin/lock'
      path: '/lock'
      fullPath: '/admin/lock'
      preLoaderRoute: typeof AdminLockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forecast': {
      id: '/admin/forecast'
      path: '/forecast'
      fullPath: '/admin/forecast'
      preLoaderRoute: typeof AdminForecastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-operations': {
      id: '/admin/bulk-operations'
      path: '/bulk-operations'
      fullPath: '/admin/bulk-operations'
      preLoaderRoute: typeof AdminBulkOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/barcodes': {
      id: '/admin/barcodes'
      path: '/barcodes'
      fullPath: '/admin/barcodes'
      preLoaderRoute: typeof AdminBarcodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wallet': {
      id: '/account/wallet'
      path: '/wallet'
      fullPath: '/account/wallet'
      preLoaderRoute: typeof AccountWalletRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/tracking': {
      id: '/account/tracking'
      path: '/tracking'
      fullPath: '/account/tracking'
      preLoaderRoute: typeof AccountTrackingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/returns': {
      id: '/account/returns'
      path: '/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/invoices': {
      id: '/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/coupons': {
      id: '/account/coupons'
      path: '/coupons'
      fullPath: '/account/coupons'
      preLoaderRoute: typeof AccountCouponsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountCouponsRoute: typeof AccountCouponsRoute
  AccountInvoicesRoute: typeof AccountInvoicesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountTrackingRoute: typeof AccountTrackingRoute
  AccountWalletRoute: typeof AccountWalletRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountCouponsRoute: AccountCouponsRoute,
  AccountInvoicesRoute: AccountInvoicesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountTrackingRoute: AccountTrackingRoute,
  AccountWalletRoute: AccountWalletRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBarcodesRoute: typeof AdminBarcodesRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminBulkOperationsRoute: typeof AdminBulkOperationsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForecastRoute: typeof AdminForecastRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLockRoute: typeof AdminLockRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOtpRoute: typeof AdminOtpRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockAdjustmentsRoute: typeof AdminStockAdjustmentsRoute
  AdminStockMovementsRoute: typeof AdminStockMovementsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarehousesRoute: typeof AdminWarehousesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBarcodesRoute: AdminBarcodesRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminBulkOperationsRoute: AdminBulkOperationsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForecastRoute: AdminForecastRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLockRoute: AdminLockRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOtpRoute: AdminOtpRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockAdjustmentsRoute: AdminStockAdjustmentsRoute,
  AdminStockMovementsRoute: AdminStockMovementsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarehousesRoute: AdminWarehousesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
