/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountWalletRouteImport } from './routes/account.wallet'
import { Route as AccountTrackingRouteImport } from './routes/account.tracking'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountReturnsRouteImport } from './routes/account.returns'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountInvoicesRouteImport } from './routes/account.invoices'
import { Route as AccountCouponsRouteImport } from './routes/account.coupons'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWalletRoute = AccountWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTrackingRoute = AccountTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInvoicesRoute = AccountInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCouponsRoute = AccountCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/coupons': typeof AccountCouponsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/tracking': typeof AccountTrackingRoute
  '/account/wallet': typeof AccountWalletRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/coupons': typeof AccountCouponsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/tracking': typeof AccountTrackingRoute
  '/account/wallet': typeof AccountWalletRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/coupons': typeof AccountCouponsRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/tracking': typeof AccountTrackingRoute
  '/account/wallet': typeof AccountWalletRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/coupons'
    | '/account/invoices'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/support'
    | '/account/tracking'
    | '/account/wallet'
    | '/account/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/coupons'
    | '/account/invoices'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/support'
    | '/account/tracking'
    | '/account/wallet'
    | '/account/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/coupons'
    | '/account/invoices'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/support'
    | '/account/tracking'
    | '/account/wallet'
    | '/account/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wallet': {
      id: '/account/wallet'
      path: '/wallet'
      fullPath: '/account/wallet'
      preLoaderRoute: typeof AccountWalletRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/tracking': {
      id: '/account/tracking'
      path: '/tracking'
      fullPath: '/account/tracking'
      preLoaderRoute: typeof AccountTrackingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/returns': {
      id: '/account/returns'
      path: '/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/invoices': {
      id: '/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/coupons': {
      id: '/account/coupons'
      path: '/coupons'
      fullPath: '/account/coupons'
      preLoaderRoute: typeof AccountCouponsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountCouponsRoute: typeof AccountCouponsRoute
  AccountInvoicesRoute: typeof AccountInvoicesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountTrackingRoute: typeof AccountTrackingRoute
  AccountWalletRoute: typeof AccountWalletRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountCouponsRoute: AccountCouponsRoute,
  AccountInvoicesRoute: AccountInvoicesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountTrackingRoute: AccountTrackingRoute,
  AccountWalletRoute: AccountWalletRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
